### ISSUE TITLE
Update roadmap

### ISSUE THREAD

**Issue by Skallwar** [ks0n/goOSe#65]

**Comment by CohenArthur** [comment]
- [ ] Decide on IPC API
- [ ] Add allocator/virtual memory manager
- [ ] Implement basic memory file system to allow loading device trees
- [ ] Implement simple ELF loader
